name: auto-approve

on:
  pull_request:
    types:
      - labeled
    branches:
      - master

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
      - run: echo
      - name: Autoapproving
        uses: hmarr/auto-approve-action@v2.0.0
        if: github.actor == 'galileo-bot'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    needs: [autoapprove]
    runs-on: ubuntu-latest
    steps:
      - name: Automerging
        uses: ridedott/merge-me-action@master
        if: github.actor == 'galileo-bot'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

