name: auto-approve

on:
  pull_request:
    branches:
      - 'version-bump/*'

jobs:
  autoapprove:
    runs-on: ubuntu-latest
    steps:
      - name: Autoapproving
        uses: hmarr/auto-approve-action@v2.0.0
#        if: github.actor == 'asyncapi-bot'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    needs: [autoapprove]
      - name: Automerging
        uses: pascalgn/automerge-action@v0.7.5
#        if: github.actor == 'asyncapi-bot'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GITHUB_LOGIN: asyncapi-bot
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "10000"
