# Auto Approve workflow is triggered
# only in master branch when pull request is labeled and label contains 'automerge'
# and base branches contains 'feature/*' in their name, it:
#   - Auto approve pull request
#   - Auto merge pull request

name: Auto-Approve

on:
  pull_request:
    types:
      - labeled
    branches:
      - master



jobs:

  autoapprove:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    runs-on: ubuntu-latest
    steps:
      - run: echo github.actor
      - name: Autoapproving
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    needs: [autoapprove]
    runs-on: ubuntu-latest
    steps:
      - name: Automerging
        uses: pascalgn/automerge-action@v0.7.5
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}

