name: "build"

on:
    push:
      branches:
        - '*'
        - '!master'
        - '!dev'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  uses: actions/setup-node@v1
         with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: npm install
      - name: Release
        id: release
        run: npm run release
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: 'chore(release): new version from bot'
          labels: automerge
          title: 'chore(release): new release'
          body: 'Version bump in package.json and package-lock.json for release'
#          branch: version-bump/${{ steps.extractver.outputs.version }}
#      - name: run tests
#        run: npm run e2e
#      - uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./dist/cypress/coverage/clover.xml
#          name: codecov-galileo
#          fail_ci_if_error: true
#      - name: Pull request
#        uses: repo-sync/pull-request@v2
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}

