name: CD

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
     branches:
       - master
  pull_request_review:
    types:
      - submitted
    branches:
      - master
  check_suite:
    types:
      - completed
    branches:
      - master

jobs:

#  autoapprove:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Autoapproving
#        uses: hmarr/auto-approve-action@v2.0.0
#        if: github.actor == 'asyncapi-bot'
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge:
#    needs: [autoapprove]
    runs-on: ubuntu-latest
    steps:
      - run: echo "ciao"
#      - name: Automerging
#        uses: pascalgn/automerge-action@v0.7.5
#        if: github.actor == 'asyncapi-bot'
#        env:
#          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
#          GITHUB_LOGIN: asyncapi-bot
#          MERGE_METHOD: "squash"
#          MERGE_COMMIT_MESSAGE: "pull-request-title"
#          MERGE_RETRIES: "10"
#          MERGE_RETRY_SLEEP: "10000"
