# Continuous Deployment workflow is triggered
# only in master branch when pull request is closed
# and base branches contains 'feature/*' in their name, it:
#   - Install deps with npm i
#   - Run release script that upgrade version with semantic versioning conventions
#   - Publish artifact (with upgraded version) to npm
#   - Create a pull request with 'automerge' label. This operation allow master to branch to receive
#     upgraded package.json after release script

name: CD

on:
  pull_request:
      types: [closed]
      branches:
       - master

jobs:
  recovery-branch-name:
    runs-on: ubuntu-latest
    outputs:
      branch-name: ${{ steps.vars.outputs.branch }}
    steps:
      - uses: mdecoleman/pr-branch-name@1.0.0
        id: vars
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
  Release:
    runs-on: ubuntu-latest
    needs: recovery-branch-name
    if: contains(needs.recovery-branch-name.outputs.branch-name, 'feature')
    steps:
      -  uses: actions/checkout@v2
      -  uses: actions/setup-node@v1
         with:
           node-version: 12
           registry-url: https://registry.npmjs.org
      - run: npm install
      - name: Release
        id: release
        run: npm run release
      - run: npm run build:galileo
      - name: publish
        working-directory: ./projects/galileo
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          author: galileo-bot <info@galileo-bot.io>
          committer: galileo-bot <info@galileo-bot.io>
          commit-message: 'chore(release): Upgraded package.json file after npm release script'
          labels: automerge
          title: 'chore(release): New release'
          body: 'Version bump in package.json and package-lock.json.'
          branch: version-bump
          delete-branch: true

