name: CD

on:
  pull_request:
      types: [closed]
      branches:
       - master

jobs:
  recovery-branch-name:
    runs-on: ubuntu-latest
    steps:
      - uses: mdecoleman/pr-branch-name@1.0.0
        id: vars
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
      -  run: echo Branch is ${{ steps.vars.outputs.branch }}
  Release:
    runs-on: ubuntu-latest
    if: contains(jobs.recovery-branch-name.steps.vars.outputs.branch, 'feature')
    steps:
      -  run: echo Branch from second job is ${{ jobs.recovery-branch-name.steps.vars.outputs.branch }}
      -  uses: actions/checkout@v2
      -  uses: actions/setup-node@v1
         with:
           node-version: 12
           registry-url: https://registry.npmjs.org
      - run: npm install
      - name: Release
        id: release
        run: npm run release
      - run: npm run build:galileo
      - name: publish
        working-directory: ./projects/galileo
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2.4.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          author: galileo-bot <info@galileo-bot.io>
          committer: galileo-bot <info@galileo-bot.io>
          commit-message: 'chore(release): new version from bot'
          labels: automerge
          title: 'chore(release): new release'
          body: 'Version bump in package.json and package-lock.json for release'
          branch: version-bump
          delete-branch: true

