# Continuous Integration workflow is triggered
# in all branches expect 'master' and 'version-bump/*', it:
#   - Install deps with npm i
#   - Run all tests
#   - Send tests to codecov
name: CI

on:
  push:
    branches:
      - '**'
      - '!master'
      - '!version-bump/*'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  uses: actions/setup-node@v1
         with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: npm install
