name: "deploy"

on:
    pull_request:
        branches:
          - master

jobs:
  release:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: "pascalgn/automerge-action@c29cef1b62bfb675777896255a70c69fc01bcfe4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: npm install
      - name: semantic-release
        run: npm run release
      - name: build
        run: npm run build:galileo
      - name: publish
        working-directory: ./dist/galileo
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
