name: "publish"

on:
    push:
        branches:
          - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.2
      - name: node
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: install
        run: npm install
      - name: publish
        run: npm run build:galileo
      - name: publish
        working-directory: ./dist/galileo
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
