name: "publish"

on:
    push:
        branches:
          - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  uses: actions/setup-node@v1
         with:
          node-version: 12
      -  run: npm install
